tap "adoptopenjdk/openjdk"
tap "github/gh"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "jesseduffield/lazygit"
tap "koekeishiya/formulae"
tap "microsoft/mssql-preview"
tap "shopify/shopify"
tap "universal-ctags/universal-ctags"
brew "python@3.8"
brew "autojump"
brew "bash"
brew "bfg"
brew "cfssl"
brew "cloc"
brew "cmake"
brew "coreutils"
brew "ctags", link: false
brew "python"
brew "findutils"
brew "fzy"
brew "git"
brew "git-delta"
brew "htop"
brew "httpie"
brew "hub"
brew "imagemagick"
brew "irssi"
brew "jq"
brew "kustomize"
brew "mas"
brew "neovim"
brew "nmap"
brew "node"
brew "node@12"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rsync"
brew "telnet"
brew "terminal-notifier", link: false
brew "terraform"
brew "testdisk"
brew "the_silver_searcher"
brew "tmux"
brew "tmuxinator"
brew "tree"
brew "watch"
brew "watchman"
brew "yarn", link: false
brew "zsh"
brew "github/gh/gh"
brew "jesseduffield/lazygit/lazygit"
brew "shopify/shopify/themekit"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD", "with-jansson"]
cask "1password"
cask "adobe-creative-cloud"
cask "adoptopenjdk8"
cask "android-studio"
cask "flipper"
cask "font-meslo-nerd-font"
cask "google-chrome"
cask "google-cloud-sdk"
cask "iina"
cask "insomnia"
cask "iterm2"
cask "ngrok"
cask "qlcolorcode"
cask "qlstephen"
cask "quicklook-json"
cask "react-native-debugger"
cask "reactotron"
cask "slack"
cask "transmission"
cask "vlc"
mas "Keynote", id: 409183694
mas "Logic Pro X", id: 634148309
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator Pro", id: 1289583905
mas "Roadblock", id: 1051436753
mas "The Unarchiver", id: 425424353
mas "Things", id: 904280696
mas "Xcode", id: 497799835
