tap "adoptopenjdk/openjdk"
tap "github/gh"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "koekeishiya/formulae"
tap "FelixKratz/formulae"
tap "koekeishiya/formulae"

brew "python@3.12"
brew "autojump"
brew "awscli"
brew "bash"
brew "bat"

# Focus borders
brew "borders"
brew "yabai"

brew "bfg"
brew "cloc"
brew "cmake"
brew "coreutils"
brew "socat"
brew "direnv"
brew "dust"
brew "elixir"
brew "fish"
brew "fisher"
brew "fmt"
brew "ffmpeg"
brew "findutils"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "gnu-sed"
brew "htop"
brew "httpie"
brew "hub"
brew "ical-buddy"
brew "imagemagick"
brew "irssi"
brew "jq"
brew "lsd"
brew "mas"
brew "neovim"
brew "nmap"
brew "node"
brew "pipx"
brew "postgresql"
brew "rbenv"
brew "ruby-build"
brew "ripgrep"
brew "rsync"
brew "sqlite"
brew "starship"
brew "swift"
brew "swiftformat"
brew "telnet"
brew "tmux"
brew "tmuxinator"
brew "trash"
brew "tree"
brew "uv"
brew "watch"
brew "watchman"
brew "websocat"
brew "weechat"
brew "youtube-dl"
brew "zlib"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "jesseduffield/lazygit/lazygit"
cask "1password"
cask "alacritty"
cask "dash"
cask "docker"
cask "firefox"
cask "font-fira-code-nerd-font"
cask "font-meslo-for-powerline"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "iina"
cask "istat-menus"
cask "netnewswire"
cask "ngrok"
cask "postico"
cask "proxyman"
cask "raycast"
cask "slack"
cask "vlc"
cask "zoom"
mas "Blackmagic RAW Speed Test", id: 1466185689
mas "Infuse", id: 1136220934
mas "Keynote", id: 409183694
mas "Logic Pro", id: 634148309
mas "Magnet", id: 441258766
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator Pro", id: 1289583905
mas "Roadblock", id: 1051436753
mas "The Unarchiver", id: 425424353
