wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32, 32, 90]
    rows: [10, 10, 10, 4, 4, 90]
  refreshInterval: 1
  mods:
    # asana:
    #   enabled: true
    #   apiKey: "1/1198724261924583:067a20005f15c2b659ed7f0358eff68d"
    #   mode: "project"
    #   projectId: 1199978439372823
    #   workspaceId: 123456789
    #   allUsers: false
    #   hideComplete: false
    #   # sections:
    #   #   - "Doing"
    #   #   - "Backlog"
    #   #   - "Complete"
    #   updateInterval: 300
    #   position:
    #     top: 0
    #     left: 0
    #     width: 5
   spacex:
      enabled: true
      apiKey: "1/1198724261924583:067a20005f15c2b659ed7f0358eff68d"
      mode: "project"
      projectId: 1199978439372823
      workspaceId: 123456789
      allUsers: false
      hideComplete: false
      # sections:
      #   - "Doing"
      #   - "Backlog"
      #   - "Complete"
      updateInterval: 300
      position:
        top: 0
        left: 0
        width: 5
        height: 6   #     height: 6
