vim.api.nvim_command("source ~/.config/nvim/plugins.vim")
require("plenary.scandir")

require("local/completion")
require("local/dap-config")
-- require("local/dash")
require("local/digraphs")
require("local/explorer")
require("local/git")
require("local/formatter")
require("local/keymap")
require("local/linter")
require("local/lsp")
require("local/neovide")
require("local/obsidian")
require("local/octo")
require("local/options")
require("local/pencil")
require("local/plugins")
require("local/projects")
require("local/status-line")
require("local/telescope")
require("local/vim-test")
require("local/neo-test")
require("local/treesitter")
require("local/theme")
require("local/react-native")
require("local/llm")

local override_dir = os.getenv("HOME") .. ".config/nvim/lua/override"
if vim.fn.isdirectory(override_dir) > 0 then
  require(override_dir)
end
