vim.api.nvim_command("source ~/.config/nvim/plugins.vim")

require("local/completion")
require("local/dap-config")
require("local/dash")
require("local/digraphs")
require("local/explorer")
require("local/keymap")
require("local/lsp")
require("local/neovide")
require("local/octo")
require("local/options")
require("local/pencil")
require("local/plugins")
require("local/projects")
require("local/status-line")
require("local/telescope")
-- require("local/vim-test")
require("local/neo-test")
require("local/treesitter")
require("local/theme")
require("local/react-native")
require("local/llm")
